version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: max-calendar-backend
    command: sh -c "sleep 7 && uvicorn backend.main:app --host 0.0.0.0 --port 9090"
    ports:
      - "9090:9090"
    environment:
      - PYTHONPATH=/app
    env_file:
      - ./backend/.env
    restart: always

  bot:
    build:
      context: .
      dockerfile: max_bot/Dockerfile
    container_name: max-calendar-bot
    command: sh -c "sleep 10 && python -u max_bot/main.py"
    environment:
      - PYTHONPATH=/max_bot
    env_file:
      - ./max_bot/.env
    restart: always

  cron:
    build:
      context: .
      dockerfile: cron_job/Dockerfile
    container_name: max-calendar-cron
    command: sh -c "sleep 15 && python -u cron_job/main.py"
    environment:
      - PYTHONPATH=/cron
    env_file:
      - ./cron_job/.env
    restart: always

  db:
    image: postgres:16
    container_name: max-calendar-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d mydb" ]
      interval: 3s
      timeout: 2s
      retries: 5

volumes:
  postgres_data: